rvm:
  - 2.4.3
before_install:
  - gem install bundler # uses newest bundler
before_script:
  - 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'
env:
  - "RAILS_VERSION=5.1.5"
  - "RAILS_VERSION=5.0.6"
