
name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # ruby-version: ['2.6.10', '3.0']
        # rails-version: ['5.2', '6.0']
        include:
          - ruby-version: '2.6.10'
            rails-version: '6.0.0'
          # - ruby-version: '3.0'
          #   rails-version: '6.1.0'
          - ruby-version: '3.0'
            rails-version: '7.0.0'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        # uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby-version }}
        env:
          RAILS_VERSION: ${{ matrix.rails-version }}
      - name: Install dependencies
        run: bundle install
      - name: Create db
        run: RAILS_ENV=test bundle exec rake db:create db:migrate --trace
      - name: Run tests
        run: bundle exec rake

